source_url: "https://xkcd.com"
dsn: "database.db"
parallel: 200
fetch_limit: 5000
scheduler_hour: 3
scheduler_minute: 0
scan_timeout: 5s
scan_limit: 10
token_max_time: 1m
rate_limit: 1
concurrency_limit: 2